- name: Deploy Apache to webservers
  hosts: ubuntu
  become: yes # Ensure you have root privileges for the tasks

  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Install apache httpd (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Start service apache2, if not started
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: start apache on boot 
      ansible.builtin.service:
        name: apache2
        enabled: true

    - name: copy index file to the nodes
      ansible.builtin.copy:
        src: index.html # on the controller
        dest: /var/www/html/index.html # on the client